### ISSUE TITLE
exception 에러가 납니다.

### ISSUE THREAD

**Issue by dooly9822** [n-andflash/ha_addons#1]
안녕하세요.

HA에서 SDS 월패드를 사용하기 위해 애드온을 설치하면
아래와 같이 2가지 현상의 로그로 인해 실행이 종료됩니다.

#1 로그파일
2021-03-16 02:23:02 ERROR    addon finished!
Traceback (most recent call last):
  File "sds.py", line 1218, in <module>
    serial_loop()
  File "sds.py", line 1120, in serial_loop
    packet = header.to_bytes(2, "big") + packet
TypeError: can't concat NoneType to bytes

#2 로그파일
2021-03-16 02:28:00 ERROR    addon finished!
Traceback (most recent call last):
  File "sds.py", line 1218, in <module>
    serial_loop()
  File "sds.py", line 1092, in serial_loop
    packet += conn.recv(remain)
TypeError: can't concat NoneType to bytes

--------------------------------------------------------------

def recv():
  ..
          if len(self._recv_buf) < count:
            return None
해당 라인을 주석처리하면 저런 현상이 발생되지 않네요.
확인 부탁드립니다.

**Comment by n-andflash** [comment]
안녕하세요, 확인이 늦었습니다. 이슈 리포트 감사합니다.

확인해보니 문제가 있는 코드네요. 현재 코드 전체적으로 dump_loop() 외에는
recv() 호출 시 원하는 만큼의 데이터가 돌아올것으로 가정하고 있기 때문에,
제안주신 라인 바로 위의 if를 while로 바꾸어 패킷이 모일때까지 blocking하는게 좋을거 같습니다.
해당 방향으로 수정해서 8.3 으로 올려두었는데 확인 부탁 드립니다.

올려주신 이슈가 제 환경에서는 재현이 되지 않고 파일이름이나 라인번호 등이 현재 github의 최신 코드는 아닌거 같은데
어떤 버전이셨는지, 별도로 수정해서 사용하시는건지 알려주실수 있을까요?

**Comment by n-andflash** [comment]
남은 이슈가 있으면 다시 오픈 부탁드려요.
