### ISSUE TITLE
엘리베이터 호출 시 KeyError: 'entrance'

### ISSUE THREAD

**Issue by 89723891** [n-andflash/ha_addons#10]
애드온 개발 감사합니다.
설치했을때 에러가 있어서 이슈남깁니다.

SDS 월패드이고, 라즈베리파이에 USB-RS485 사용해서 연결했습니다.
조명등 여타 기능 잘 동작합니다만
entrance 모드 minimal 로 두고 엘리베이터 호출 시 KeyError 가 납니다.
전체소등은 잘 동작합니다.
entrance 모드를 full 로 할 경우 엘리베이터 호출은 되나 전체소등이 동작하지 않습니다.

참고로 현관 쪽 스위치에는 가스차단, 일괄소등 2개 버튼만 있는 구성입니다.

에러 로그입니다.
> 08:08:39 INFO     recv. from HA:   sds/virtual/entrance/ev/command = ON
> Exception in thread paho-mqtt-client-sds_wallpad-1733752192.9697025:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
>     self.run()
>     ~~~~~~~~^^
>   File "/usr/local/lib/python3.13/threading.py", line 992, in run
>     self._target(*self._args, **self._kwargs)
>     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4523, in _thread_main
>     self.loop_forever(retry_first_connection=True)
>     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 2297, in loop_forever
>     rc = self._loop(timeout)
>   File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1686, in _loop
>     rc = self.loop_read()
>   File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 2100, in loop_read
>     rc = self._packet_read()
>   File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 3142, in _packet_read
>     rc = self._packet_handle()
>   File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 3808, in _packet_handle
>     return self._handle_publish()
>            ~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4145, in _handle_publish
>     self._handle_on_message(message)
>     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4501, in _handle_on_message
>     on_message(self, self._userdata, message)
>     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/srv/sds_wallpad.py", line 830, in mqtt_on_message
>     mqtt_virtual(topics, payload)
>     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "/srv/sds_wallpad.py", line 715, in mqtt_virtual
>     virtual_trigger[device][(trigger, payload)] = time.time()
>     ~~~~~~~~~~~~~~~^^^^^^^^
> KeyError: 'entrance'

소스 코드의 init_virtual_device 함수에서 'minimal' 모드일때 virtual_trigger 변수 지정하는 부분이 없어서 위 에러가 나는 것 같습니다.
확인 가능하실까요.

**Comment by ikjoon-son** [comment]
minimal mode를 사용하는 분은 지난 몇년간 없었나봅니다... ㅎㅎ

상황이 여의치 않아서 올려주신 내용만 보고 테스트 없이 수정사항 일단 올렸는데, 확인해보시고
오류가 있으면 댓글 주시거나 수정해서 pull request 주셔도 좋습니다.

minimal 세팅으로 엘베호출 잘 되는지도 알려주시면 더 좋겠네요.

**Comment by 89723891** [comment]
방금 테스트해봤는데 minimal 에서 엘베호출, 일괄소등 에러 없이 잘 동작합니다! 수정감사합니다.
