### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by wooooooooooook** [n-andflash/ha_addons#3]
라즈베리파이4b에 hassOS환경이고 addon으로 설치했습니다

s6-overlay-suexec: fatal: can only run as pid 1
이 에러가 나면서 동작하지않습니다.
제거, 재부팅 후 재설치해봐도 마찬가지입니다
의심되는 부분은 8.2버전이었다가 업데이트를 하니 8버전으로 바뀐뒤 증상이방생한것같습니다.
해결이가능할까요?

**Comment by n-andflash** [comment]
안녕하세요,

애드온을 https://github.com/HAKorea/addons 저장소가 아닌
https://github.com/n-andflash/ha_addons 에서 다시 설치해주세요.
현재 최신버전은 9 입니다.

**Comment by wooooooooooook** [comment]
해결하였습니다 감사합니다
