### ISSUE TITLE
checksum fail! b0796128ae, 2e

### ISSUE THREAD

**Issue by scpregistro** [n-andflash/ha_addons#4]
WARNING  checksum fail! b0796128ae, 2e 

해당 경고가 발생하여 살펴보니, 

![image](https://user-images.githubusercontent.com/5725100/187344956-96118254-b2a7-4f46-ab45-bac0e7949371.png)

해당 패킷의 B0796128, AE7...  부분의 패킷이 잘못 잘려지는 것 같습니다. 그럴까요?

**Comment by n-andflash** [comment]
덤프 전체적으로 패킷 중 00 바이트들이 누락되어 있네요. 설정이나 연결된 라인 상태에 문제가 있는거 같습니다.
혹시 아래 이미지처럼 생긴 USB to RS485를 사용하신다면 해당 커넥터 불량일 가능성이 매우 높으니 다른 것으로 교체하세요.
![externalFile](https://user-images.githubusercontent.com/67410137/187360273-0f767306-7d00-48fc-a4ee-803f120dc7ba.jpg)

**Comment by scpregistro** [comment]
빠른 응답에 감사드립니다.

의견 주신것처럼 00이 누락된 패킷과 그렇지 않는 패킷이 나타나는 것 같습니다.

그런데, 유일하게 해당 패킷만 체크섬 에러로 표출되는 것일까요?

![image](https://user-images.githubusercontent.com/5725100/187369954-3487c777-830c-4a9f-bbd2-a38ddfd36eab.png)

**Comment by scpregistro** [comment]
제품은 EW11을 사용하고 있습니다.
![image](https://user-images.githubusercontent.com/5725100/187370505-cecdffab-b7e5-4da8-a052-a39aee3073c1.png)

**Comment by n-andflash** [comment]
네... 체크섬이 XOR 방식이라 00값의 유무가 계산 결과에 영향이 없다보니 체크섬으로는 해당 문제를 제대로 못잡고 있네요.

EW11 설정 페이지에서 8-Even-1 설정 잘 돼있는지 다시한번 확인해보시구요,
SerialPortMon TCP Client로 접속해서 월패드 애드온과 상관없는 문제가 맞는지도 체크해보시면 좋을거 같습니다.
https://blog.daum.net/pg365/276

**Comment by scpregistro** [comment]
Parity가 None로 되어 있어 Even으로 변경 후 checksum 오류가 사라진 것 같습니다.

![image](https://user-images.githubusercontent.com/5725100/187385214-9975fc00-5486-49d5-80f7-77f3e8ff082f.png)

감사합니다.
