### ISSUE TITLE
set temperature 구문이 없는지 궁금합니다.

### ISSUE THREAD

**Issue by ohnggni** [n-andflash/ha_addons#5]
ew11로 socket 모드로 구현하여 
- 조명
- 난방
두가지를 활용하고 있습니다.

난방 활용시, lovelace상에서 슬라이더 등을 이용하여 target 온도 설정하여 잘 쓰고 있으나,
자동화를 구현하려고 보니, HVAC on/off만 가능한 것으로 보입니다. set temperature 같은(또는 유사한) entity가 보이지 않습니다.

그런데 또 ha랑 연결된 아이폰 홈킷 자동화로 하면, 정해진 시간에 특정온도로 올리는 것은 가능한데, HA에서 하는 것 보다 자유도가 떨어지네요.

entity에 target온도를 설정할 구문 반영이 가능한지 궁금합니다. (제 질문이 맞는 질문인지 잘 모르겠네요)

**Comment by n-andflash** [comment]
애드온에서 난방은 climate.sds_thermostat_N 형태의 entity로 지원하며, 해당 entity는 on/off 외에도 temperature,  current_temperature 등의 attribute를 제공하고 climate.set_temperature 등의 service 를 지원합니다.

https://www.home-assistant.io/integrations/climate/

**Comment by n-andflash** [comment]
![Screenshot_20221219_225620_Home Assistant](https://user-images.githubusercontent.com/67410137/208441791-7d702c7b-a7b5-4402-a7ab-a3144137b9ae.png)

**Comment by ohnggni** [comment]
> ![Screenshot_20221219_225620_Home Assistant](https://user-images.githubusercontent.com/67410137/208441791-7d702c7b-a7b5-4402-a7ab-a3144137b9ae.png)

아, 이게 자동화 메뉴에서도 action에  call service로 하면  되겠군요. 빠른 답변 감사드립니다. ^^
