### ISSUE TITLE
에너지 사용량 구현 관련 도움 요청

### ISSUE THREAD

**Issue by ohnggni** [n-andflash/ha_addons#6]
HA카페에 packet 덤프, 사진, 설명 등 업데이트 하여 다시 질문올렸습니다.
https://cafe.naver.com/koreassistant/12061
-----------------------------------------------------------------

안녕하세요? 에너지 사용량 구현 관련해서 도움 요청드리고자 합니다.
저는 SHT-7307XM 모델의 월패드 사용 중이며, 본 애드온으로 조명, 보일러까지는 제어하여 사용중이나, 에너지 사용량이 나오지 않아(월패드에는 나옴) 방법을 찾던 중, 아래와 같은 포트를 찾아, Y형 커플러, EE11 등을 연결하여 패킷을 살펴보니
<img width="373" alt="KakaoTalk_Photo_2023-02-18-00-31-56" src="https://user-images.githubusercontent.com/33609687/219696922-526e23fe-7bb6-459f-9d35-5988c6ec4f7c.png">

에너지 사용량으로 보이는 부분을 찾기는 찾았습니다(아래참조). 그러나 현재 애드온으로는 검색이 되지 않고, 패킷분석해 놓은 페이지도 살펴보았으나, 형식이 좀 다른 것 같습니다. 이 다음부터는 어떻게 구현해야할지 도움 요청드립니다.

2023-02-17 22:01:11중 A0 75 0F 17 02 02 33 02 00 83 04 00 10 49
-> 17 02가 23년 2월?, 02 33 02가 233.02(전기), 00 83 04가 83.04(가스), 00 10 49가 10.49(수도)
2023-02-17 22:01:19중  A0 75 0F 17 01 04 43 09 01 76 30 00 17 03
-> 17 01가 23년 1월?, 04 43 09가 443.09(전기), 01 76 30이 176.30(가스), 00 17 03이 17.03(수도)
[wallpad_dump.log](https://github.com/n-andflash/ha_addons/files/10768388/wallpad_dump.log)

**Comment by n-andflash** [comment]
제가 며칠간 외출 중이라 확인이 늦고 있습니다. 조만간 살펴보고 다시 댓글 드리겠습니다.

**Comment by ohnggni** [comment]
> 제가 며칠간 외출 중이라 확인이 늦고 있습니다. 조만간 살펴보고 다시 댓글 드리겠습니다.

관심가져주셔서 너무 감사드립니다.

일단 저도 패킷보면서 좀 정리를 해보고 있습니다. 뭔가 규칙성도 있는 것 같고 그런데, 도움이 될 지 모르겠으나, 제가 정리 중인 엑셀파일도 공유해봅니다. 
- 음영 없는 것이 normal이고, 
- 붉은 색이 사용량 수치가 명시적으로 나온(특히 A0 75로 시작하는...), 그리고
- 노란색은 후속패킷 그룹인듯 합니다. 
- 붉은 색 음영이 두 개 인거는 제가 금월 치 조회하고, 전월 치 까지 조회해봤기 때문입니다.
- 잘은 모르지만 일단 패킷이 normal대비 다르게 보이는 거는 bold체로라도 표시해 봤습니다.

[wpad_energy_packet.xlsx](https://github.com/n-andflash/ha_addons/files/10778115/wpad_energy_packet.xlsx)

**Comment by n-andflash** [comment]
지금 패킷 관찰하시는 라인이 조명, 보일러 제어하는 RS485 라인과는 별개이신거죠?
이거 아마 여러 세대에서 공용으로 사용하는 라인인거 같습니다. A0 이 ohnggni님 세대 고유번호거나 뭐 그런식일 겁니다.
예전에 비슷한 패킷 관찰하신 분의 글이 카페 어디에 있는데 지금 찾을수가 없네요.

일단 보이는건 81\~99까지, A0\~B7까지 여러 세대가 같은 라인을 공유하고 있는 것으로 보이고,
중앙 서버에서 xx 33 00 00 PT 다섯 바이트로 각 세대 점검을 하면 평상시에는 80 33 00 00 08 로 keepalive 응답을 하는데,
80 75 05 00 F0 으로 응답을 하면 그 다음번 A0 댁 차례에 A0 75 로 시작하는 정보 패킷을 보내주고
80 76 05 00 F3 으로 응답을 하면 그 다음번 A0 댁 차례에 A0 76 로 시작하는 정보 패킷을 보내주는게 보이네요.

B8~BC 처럼 응답하지 않는 세대 번호에 대해서 B8 71 00 01 04와 같이 스캔을 해보는 부분도 보입니다.

결국 장치 스캔, keepalive, 통신 순서 등은 삼성SDS 가정 내부 라인과 같은 컨셉이네요 (패킷은 다르지만).
[애드온의 인터폰 구현](https://github.com/n-andflash/ha_addons/blob/master/sds_wallpad/DOCS_PACKETS.md#%EC%9D%B8%ED%84%B0%ED%8F%B0-a1a6) 과 같은 방법으로 구현이 가능할 것이기는 합니다...

다만 이 저장소의 애드온이 통신하는 라인과는 다른 라인이기 때문에 같은 애드온에서 지원하는 것은 모양새가 이상합니다.
별개의 애드온이나 스크립트를 만들어야 하는 부분이고 (물론 제 애드온에서 시작을 하는것도 한가지 방법이겠지만)
저희 집 월패드는 세대 외부 통신이 이더넷 방식이라... 제가 도와드릴수 있는 부분이 많지는 않네요.

**Comment by ohnggni** [comment]
네, 패킷 관찰 라인이 조명, 보일러 제어하는 것과는 별개 라인 맞습니다. 그리고 비슷한 패킷 관찰글은 아마도 [이 글](https://cafe.naver.com/koreassistant?iframe_url_utf8=%2FArticleRead.nhn%253Fclubid%3D29860180%2526articleid%3D6761) 같네요. 

일단 패킷이 나오니깐, 쉽게 갈 줄 알았는데;;; 공사가 만만치가 않군요. 
**그런데 혹시 다른 패킷들처럼(eg. 조명, 보일러 등) 단순히 serialportmon 같은 것으로 패킷을 쏴주면 작동이 되게(A0 75...)할 방법은 없겠는지요?** 사실 80 75 05 00 F0로 응답하는 부분이 월패드 부가메뉴에 들어가서 원격검침 결과를 조회하는 행동(동작)을 할 때 나오는 패킷으로 생각되어, 어제부터 serialportmon으로 80 75 05 00 F0을 계속 쏴보고 있는데 전혀 먹히지도 않고, 몇번 쏘다보면 A0 75로 시작하기는 하나 수치부분은 00 00 00 00...등으로 가득한 패킷이 등장하는 경우가 간혹 있기는 합니다만, 연결만 시켜놔도 수많은 패킷들이 쏟아져 나오는 상황이다보니, 타이밍(?)이 맞는 건지도 잘 모르겠습니다.

단순히 A0 75로 시작하는 정보 패킷이 나오게 하는 간단한(?) 방법만 고안하면, 꼭 애드온 형태가 아니더라도 log파일에서 정보 패킷 부분만 추출해서 어딘가에 표현하는 방법도 생각해 볼수 있을 것 같습니다. 아니면 스위치봇 같은 것으로 주기적으로 터치라도 하게 할 수 있나(터치해서 화면 나올 때 정보 패킷도 나올 것이고 그때의 로그를 활용) 등도 어떨까 싶고요.

**Comment by n-andflash** [comment]
링크 주신 글이 맞네요 ㅎㅎ

인터폰이나 현관스위치(엘리베이터 호출)와 같은 수준의 구현이 필요합니다.
즉 라인을 지켜보고 있다가 중앙 서버에서 A0 33 00 00 0A 를 보낸 순간에 정확히 80 75 05 00 F0 를 보내야
중앙 서버에서 잠시 후에 A0 75 ... 를 돌려받을 수 있습니다. 그동안 월패드에선 아무 패킷도 못보내게 끊어야 하구요.
다른 애드온이나 컴포넌트들을 보면 타이밍이 우연히 맞을 때까지 패킷을 마구잡이로 보내는 구현 방식도 있는데
공용 라인에서 그런 행동을 했다간 건물 전체에 사달이 날겁니다. 

스위치봇까지 생각하신다면... 월패드에서 "원격 검침" 메뉴를 눌렀을 때
월패드가 타이밍에 맞게 80 75 05 00 F0 을 보낸 후 돌려받은 A0 75 ... 를 화면에 표시하는 방식이기 때문에
스위치봇으로 원격 검침을 누르고 A0 75 패킷을 추출하는 것도 방법이 되기는 합니다.

**Comment by ohnggni** [comment]
소중한 조언 감사드립니다. 상황을 이해하는데 많은 도움이 됐습니다. 아이디어를 좀 더 구체화해서 도전해봐야겠어요 ^^
고맙습니다~~

**Comment by ohnggni** [comment]
안녕하세요? 오랜만에 업데이트 남깁니다. 비록 매우 깔끔하게 해결하지는 못했지만, 핑거봇 + wallpad dump addon을 활용하여 나름 자동화(?)까지 마쳤습니다. 검침패킷이 나오는 응답패킷을 정확한 타이밍에 끼워넣는 것이 이런 저런 방법들을 써봤는데 끝내 안됐고, 그 사이 알리에서 핑거봇이 배송되어 오는 바람에 다음과 같은 시퀀스로 대략 자동화 구현했습니다.

1) 정해진 시간이 되면 Wallpad dump addon이 시작됨
2) 이어서 핑거봇이 월패드 화면(구형이라 감압식터치임)에 부가 메뉴 버튼을 클릭해줌 
   → 원격검침 결과 화면이 디스플레이 되면서 관련 패킷이 발생
3) Wallpad dump addon을 중지함
4) 생성된 addon log파일에서 검침패킷을 파이썬으로 크롤링(?)하여 value 값으로 환산
5) 환산된 값을 MQTT 토픽 메시지로 발행
6) MQTT sensor/template가 그 값을 대시보드에 표현 and utilitiy meter로 구현하여 에너지 사이드패널에 구현

구현하느라 손이 많이 가긴 했는데, 그래도 만들어주신 dump 애드온 덕에 훨씬 쉽게 완성은 했습니다. 사진보면 월패드 화면을 부득이 좀 가리게 되는데, 마침 사용빈도가 매우 낮은 메뉴버튼들 쪽이라 큰 무리는 없네요.

좋은 애드온 개발해 주셔서 다시한번 너무 감사드립니다. ^^

![IMG_5597](https://user-images.githubusercontent.com/33609687/223324088-6532ff9b-dd33-48e1-9abd-e2599472576f.jpeg)
<img width="380" alt="스크린샷 2023-03-07 오후 1 56 34" src="https://user-images.githubusercontent.com/33609687/223324597-29f7f192-6929-4348-b6f5-65afd12b35bd.png">
<img width="1107" alt="스크린샷 2023-03-07 오후 1 57 09" src="https://user-images.githubusercontent.com/33609687/223324611-2aabda4b-a0c1-4d62-8b84-c5e614584ca0.png">

**Comment by n-andflash** [comment]
쉽지 않은 상황으로 보였는데 사람 손 필요한 부분 없도록 자동화를 하셨네요 ㅎㅎ 축하드립니다~
