### ISSUE TITLE
반복적인 애드온 재시작!

### ISSUE THREAD

**Issue by watereye99** [n-andflash/ha_addons#7]
안녕하세요. 
최근 HA에 입문해서 월패드 애드온을 적용했는데, 애드온이 반복적으로 중단되었다 재실행되고 있습니다.

에러 로그는 아래와 같습니다.

감사합니다.

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/srv/sds_wallpad.py", line 1317, in <module>
    serial_loop()
  File "/srv/sds_wallpad.py", line 1243, in serial_loop
    logger.warning("initiate aggressive send mode!", scan_count)
Message: 'initiate aggressive send mode!'
Arguments: (0,)
14:53:15 WARNING  unhandled exception device reports readiness to read but returned no data (device disconnected or multiple access on port?)
14:53:15 WARNING  restart addon ... (serial connection lost!)
14:53:17 INFO     initialize serial...
14:53:17 INFO     initialize mqtt...
14:53:17 INFO     start loop ...
14:53:39 INFO     running stable...

**Comment by n-andflash** [comment]
안녕하세요,

일단 동작이 아예 안되신다는건지, 주기적으로 재시작을 한다는건지 알아야 하는데 모르겠습니다.

- USB to RS485 사용하시는거죠? 라인은 어디에 연결하셨나요?
- 주기적이라면 애드온 처음 사용하실 때부터 그랬었나요? 언제쯤인가요?
- 주기적이라면 빈도는 어느정도인가요?
- 혹시 SerialPortMon이나 dump_time 기능으로 패킷 덤프 확인해보셨는지요? 거기서는 이상이 없었나요?

**Comment by watereye99** [comment]
확인 감사합니다.
제 지식으로 이해하고 답변 가능한 범위 내에서 최대한 정리했습니다.

**USB to RS485 사용하시는거죠? 라인은 어디에 연결하셨나요?**
ㄴ USB to RS485 사용했습니다. 라인은 인터넷 단자함의 홈게이트 웨이에 연결했습니다.

**주기적이라면 애드온 처음 사용하실 때부터 그랬었나요? 언제쯤인가요?**
ㄴ 이전 버전으로 처음 설치했고, 당시에는 전등 일괄소등만 디바이스로 등록되었고, 실제 사용 가능했습니다. 아쉽게도 엘리베이터 호출은 못 찾아서인지 등록이 안 되었구요,
ㄴ 주기적인 애드온 재 시작은 신규 버전 업데이트 이후 바로 발생했습니다. 이전 버전에서는 잡히지 않던 엘레베이터 호출과 가스 잠금 스위치가 추가적으로 잡혔지만, 애드온이 반복적으로 재시되는지라 이전 버전에서는 작동하던 전등 일괄 소등 버튼과 함꼐 모두 작동은 하지 않았습니다.

**주기적이라면 빈도는 어느정도인가요?**
ㄴ 답변을 적는 지금 로그를 확인해보니 가장 최근의 애드온 재시작은 아래 로그 처럼 약 30초 정도 걸렸네요.

07:20:27 WARNING  unhandled exception device reports readiness to read but returned no data (device disconnected or multiple access on port?)
07:20:27 WARNING  restart addon ... (serial connection lost!)

07:20:56 WARNING  unhandled exception device reports readiness to read but returned no data (device disconnected or multiple access on port?)
07:20:56 WARNING  restart addon ... (serial connection lost!)

**혹시 SerialPortMon이나 dump_time 기능으로 패킷 덤프 확인해보셨는지요? 거기서는 이상이 없었나요?**
ㄴ 패킷 덤프 프로그램으로 패킷을 조금 보긴 했지만, 제 지식으로 패킷만으로 문제를 인지하기는 어려웠습니다.
ㄴ 다만, 집의 전등 제어가 월패드에서는 일괄 On/Off만 가능하고, 개별 On/Off는 불가능한 점. 전등 개별 On/Off는 건설사에서 제공하는 별도 App에서는 작동하고 있다는 점. 그리고 월패드 Add-On 첫 시동시 관련 로그가 주르륵 뜨다가 죽는 점 등을 볼 때, 저희 집의 전등 제어 관련 패킷이 일반적인 삼성 월패드와 다르게 되어 있고, 이 부분에서 문제가 발생했을 수도 있지 않을까 하는 의심이 드네요.
ㄴ 아래는 애드온 첫 시동 후 초기화까지의 Log입니다.

[Info] run sds_wallpad.py ...
07:22:58 INFO     addon version 9.7
07:22:58 INFO     initialize serial...
07:22:59 INFO     initialize mqtt...
07:22:59 INFO     waiting MQTT connected ...
07:22:59 INFO     MQTT connect successful!
07:22:59 INFO     Add new device:  homeassistant/switch/sds_wallpad/sds_elevator/config
07:22:59 INFO     Add new device:  homeassistant/switch/sds_wallpad/sds_gas_cutoff/config
07:22:59 INFO     initial state:   sds/virtual/entrance/ev/state = OFF
07:22:59 INFO     initial state:   sds/virtual/entrance/gas/state = OFF
07:22:59 INFO     subscribe homeassistant/status
07:22:59 INFO     subscribe sds/virtual/+/+/command
07:22:59 INFO     subscribe sds/+/+/+/command
07:23:00 INFO     start loop ...
07:23:03 INFO     Add new device:  homeassistant/switch/sds_wallpad/sds_light_cutoff_1/config
07:23:05 INFO     publish to HA:   sds/light/1/power1/state = ON (b079010149)
07:23:05 INFO     publish to HA:   sds/light/1/power2/state = OFF (b079010149)
07:23:05 INFO     publish to HA:   sds/light/1/power3/state = OFF (b079010149)
07:23:05 INFO     publish to HA:   sds/light/1/power4/state = OFF (b079010149)
07:23:05 INFO     publish to HA:   sds/light/1/power5/state = OFF (b079010149)
07:23:05 INFO     publish to HA:   sds/light/1/power6/state = OFF (b079010149)
07:23:05 INFO     publish to HA:   sds/light/1/power7/state = OFF (b079010149)
07:23:05 INFO     publish to HA:   sds/light/1/power8/state = OFF (b079010149)
07:23:05 INFO     publish to HA:   sds/light/2/power1/state = OFF (b07902004b)
07:23:05 INFO     publish to HA:   sds/light/2/power2/state = OFF (b07902004b)
07:23:05 INFO     publish to HA:   sds/light/2/power3/state = OFF (b07902004b)
07:23:05 INFO     publish to HA:   sds/light/2/power4/state = OFF (b07902004b)
07:23:05 INFO     publish to HA:   sds/light/2/power5/state = OFF (b07902004b)
07:23:05 INFO     publish to HA:   sds/light/2/power6/state = OFF (b07902004b)
07:23:05 INFO     publish to HA:   sds/light/2/power7/state = OFF (b07902004b)
07:23:05 INFO     publish to HA:   sds/light/2/power8/state = OFF (b07902004b)
07:23:05 INFO     publish to HA:   sds/light/3/power1/state = OFF (b07903004a)
07:23:05 INFO     publish to HA:   sds/light/3/power2/state = OFF (b07903004a)
07:23:05 INFO     publish to HA:   sds/light/3/power3/state = OFF (b07903004a)
07:23:05 INFO     publish to HA:   sds/light/3/power4/state = OFF (b07903004a)
07:23:05 INFO     publish to HA:   sds/light/3/power5/state = OFF (b07903004a)
07:23:05 INFO     publish to HA:   sds/light/3/power6/state = OFF (b07903004a)
07:23:05 INFO     publish to HA:   sds/light/3/power7/state = OFF (b07903004a)
07:23:05 INFO     publish to HA:   sds/light/3/power8/state = OFF (b07903004a)
07:23:05 INFO     publish to HA:   sds/light/5/power1/state = OFF (b07905004c)
07:23:05 INFO     publish to HA:   sds/light/5/power2/state = OFF (b07905004c)
07:23:05 INFO     publish to HA:   sds/light/5/power3/state = OFF (b07905004c)
07:23:05 INFO     publish to HA:   sds/light/5/power4/state = OFF (b07905004c)
07:23:05 INFO     publish to HA:   sds/light/5/power5/state = OFF (b07905004c)
07:23:05 INFO     publish to HA:   sds/light/5/power6/state = OFF (b07905004c)
07:23:05 INFO     publish to HA:   sds/light/5/power7/state = OFF (b07905004c)
07:23:05 INFO     publish to HA:   sds/light/5/power8/state = OFF (b07905004c)
07:23:05 INFO     publish to HA:   sds/light/6/power1/state = ON (b07906014e)
07:23:05 INFO     publish to HA:   sds/light/6/power2/state = OFF (b07906014e)
07:23:05 INFO     publish to HA:   sds/light/6/power3/state = OFF (b07906014e)
07:23:05 INFO     publish to HA:   sds/light/6/power4/state = OFF (b07906014e)
07:23:05 INFO     publish to HA:   sds/light/6/power5/state = OFF (b07906014e)
07:23:05 INFO     publish to HA:   sds/light/6/power6/state = OFF (b07906014e)
07:23:05 INFO     publish to HA:   sds/light/6/power7/state = OFF (b07906014e)
07:23:05 INFO     publish to HA:   sds/light/6/power8/state = OFF (b07906014e)
07:23:05 INFO     publish to HA:   sds/light/7/power1/state = OFF (b07907004e)
07:23:05 INFO     publish to HA:   sds/light/7/power2/state = OFF (b07907004e)
07:23:05 INFO     publish to HA:   sds/light/7/power3/state = OFF (b07907004e)
07:23:05 INFO     publish to HA:   sds/light/7/power4/state = OFF (b07907004e)
07:23:05 INFO     publish to HA:   sds/light/7/power5/state = OFF (b07907004e)
07:23:05 INFO     publish to HA:   sds/light/7/power6/state = OFF (b07907004e)
07:23:05 INFO     publish to HA:   sds/light/7/power7/state = OFF (b07907004e)
07:23:05 INFO     publish to HA:   sds/light/7/power8/state = OFF (b07907004e)
07:23:06 INFO     publish to HA:   sds/light/8/power1/state = OFF (b079080041)
07:23:06 INFO     publish to HA:   sds/light/8/power2/state = OFF (b079080041)
07:23:06 INFO     publish to HA:   sds/light/8/power3/state = OFF (b079080041)
07:23:06 INFO     publish to HA:   sds/light/8/power4/state = OFF (b079080041)
07:23:06 INFO     publish to HA:   sds/light/8/power5/state = OFF (b079080041)
07:23:06 INFO     publish to HA:   sds/light/8/power6/state = OFF (b079080041)
07:23:06 INFO     publish to HA:   sds/light/8/power7/state = OFF (b079080041)
07:23:06 INFO     publish to HA:   sds/light/8/power8/state = OFF (b079080041)
07:23:06 INFO     publish to HA:   sds/cutoff/1/power/state = ON (b0520163)
07:23:08 WARNING  check loop count fail: there are no A1! try A5...
07:23:08 INFO     publish to HA:   sds/light/4/power1/state = OFF (b07904004d)
07:23:08 INFO     publish to HA:   sds/light/4/power2/state = OFF (b07904004d)
07:23:08 INFO     publish to HA:   sds/light/4/power3/state = OFF (b07904004d)
07:23:08 INFO     publish to HA:   sds/light/4/power4/state = OFF (b07904004d)
07:23:08 INFO     publish to HA:   sds/light/4/power5/state = OFF (b07904004d)
07:23:08 INFO     publish to HA:   sds/light/4/power6/state = OFF (b07904004d)
07:23:08 INFO     publish to HA:   sds/light/4/power7/state = OFF (b07904004d)
07:23:08 INFO     publish to HA:   sds/light/4/power8/state = OFF (b07904004d)
07:23:14 WARNING  check loop count fail: there are no A5! try C2...
07:23:18 WARNING  unhandled exception device reports readiness to read but returned no data (device disconnected or multiple access on port?)
07:23:18 WARNING  restart addon ... (serial connection lost!)

ㄴ 전등 관련 로그는 첫 시동 후 일정 기간 찍히다가, 몇 시간(?) 후에는 첫 글에 적은 에러 로그만 남기고 더 이상 뜨지 않긴 합니다.

ㄴ 마지막으로 아래는 올려주신 패킷 덤프 프로그램의 HA 로그 화면에서 확인 가능한 패킷입니다.
07:23:00 INFO      00 00 00 50
07:23:00 INFO      AE 7C 03 00 00 00 00 51
07:23:00 INFO      AE 7C 04 00 00 00 00 56
07:23:00 INFO      AB 41 00 6A
07:23:00 INFO      AD 41 00 6C B0 41 00
07:23:00 INFO      71
07:23:00 INFO      AD 52 00 7F B0
07:23:00 INFO      52 01 63
07:23:02 INFO      79 04 00 51 B0 79
07:23:18 INFO      B0 41 00 71
07:23:18 INFO      AD 52 00 7F
07:23:18 INFO      B0 52 01 63
07:23:20 INFO      79 01 00 54
07:23:24 INFO      AE 7C 01 00 00 00 00 53
07:23:39 INFO      00 00 51
07:23:45 INFO      7C
07:23:51 INFO      03 00 00 00 00 51
07:23:56 INFO      79
07:24:00 INFO      7C 03 00 00 00 00 51
07:24:00 INFO      AE 7C 04 00 00 00 00 56
07:24:00 INFO      AB 41 00 6A
07:24:00 INFO      AD 41 00 6C B0
07:24:00 INFO      41 00 71
07:24:00 INFO      AD 52 00 7F
07:24:00 INFO      B0 52 01 63
07:24:12 INFO      AC
07:24:15 INFO      52 00 7F B0 52
07:24:18 INFO      7C 01
07:24:18 INFO      02 00 00 00 00 50
07:24:18 INFO      AE 7C 03 00 00 00 00 51
07:24:18 INFO      AE 7C 04 00 00 00
07:24:18 INFO      00 56
07:24:18 INFO      AB
07:24:18 INFO      41 00 6A
07:24:18 INFO      AD 41 00 6C
07:24:18 INFO      B0 41 00 71
07:24:18 INFO      AD 52 00 7F
07:24:18 INFO      B0 52 01 63
07:24:32 INFO      05 00
07:24:33 INFO      52 00 7F
07:24:36 INFO      AD 52 00
07:24:53 INFO      06 01 4E
07:25:08 INFO      79 06 00 53
07:25:09 INFO      7C 02 00 00 00 00 50
07:25:21 INFO      41 00 6A
07:25:27 INFO      41 00 6A
07:25:33 INFO      79 08 00 41
07:25:39 INFO      7C 04 00 00 00 00 56
07:25:51 INFO      52 00
07:25:51 INFO      7F B0 52 01 63
07:25:53 INFO      79 03 00 4A
07:25:53 INFO      79 04 00 51
07:26:24 INFO      02 00 00 00 00 50
07:26:26 INFO      79 02 00 57 B0
07:26:30 INFO      79 08 00 41
07:26:57 INFO      6C
07:27:12 INFO      41 00 6A
07:27:41 INFO      79 06 00
07:27:48 INFO      6C
07:27:51 INFO      7C 04 00 00 00 00 56
07:28:11 INFO      79
07:28:21 INFO      52 01 63
07:28:32 INFO      02 00 4B
07:28:32 INFO      79 05 00 4C
07:28:39 INFO      00 6A
07:28:45 INFO      00 71
07:28:47 INFO      05 00 50
07:28:51 INFO      AE 7C 02 00 00
07:28:51 INFO      00 00 50
07:28:51 INFO      AE
07:28:51 INFO      7C 03 00 00 00 00 51
07:28:51 INFO      AE 7C 04 00 00 00 00 56
07:28:51 INFO      AB 41 00 6A
07:28:51 INFO      AD 41 00 6C B0 41 00
07:28:51 INFO      71
07:28:51 INFO      AD 52 00 7F B0 52 01
07:28:51 INFO      63
07:28:59 INFO      01 4E
07:28:59 INFO      AC 79 07 00 52 B0
07:28:59 INFO      79 07 00 4E
07:29:00 INFO      AC 79 08 00 5D
07:29:00 INFO      B0 79 08 00 41
07:29:00 INFO      AE 7C 01 00 00 00 00
07:29:00 INFO      53
07:29:00 INFO      AE 7C 02 00
07:29:00 INFO      00 00 00 50
07:29:00 INFO      AE 7C 03 00 00 00 00 51
07:29:00 INFO      AE 7C 04 00 00 00 00 56
07:29:00 INFO      AB 41 00 6A
07:29:00 INFO      AD 41 00 6C B0 41 00
07:29:00 INFO      71
07:29:00 INFO      AD 52 00 7F B0
07:29:00 INFO      52 01 63
07:29:09 INFO      08 00 41
07:29:29 INFO      01 00 54
07:29:29 INFO      79 04 00 4D
07:29:48 INFO      01 00 00 00 00 53
07:29:51 INFO      41 00 6A
07:29:56 INFO      B0 79 06 01 4E
07:30:03 INFO      7C 02 00 00 00 00 50

추가적으로 제가 뽑아낼 수 있는 Data가 있다면, 알려주세요!

감사합니다.

**Comment by n-andflash** [comment]
덤프가 수초~수십초씩 멈췄다가 다시 올라오는걸 보면 결선불량이나 USB to RS485 불량인걸로 보입니다. 정상적인 경우 매 초 여러줄의 패킷이 올라옵니다.

선을 뺐다가 단단히 다시 연결하면 해결이 될수도 있고, 혹시 아래처럼 생긴 USB to RS485 쓰신다면 다른 제품으로 교체해보세요. 불량률이 굉장히 높았습니다.
![187360273-0f767306-7d00-48fc-a4ee-803f120dc7ba](https://github.com/n-andflash/ha_addons/assets/67410137/a36ca08a-c392-43ac-89ac-3505515f557e)

**Comment by watereye99** [comment]
저렴한 제품은 문제가 있다는 이야기를 들어 "넥스트 USB to RS422/485 1포트 컨버터"로 구입해 사용 중입니다.

조언 주신 것을 참고해 다시 연결 후 확인해 보겠습니다.

감사합니다.
